"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p+hdxipq!py1yf!wl*@r$85s0tz8k3n1)#x28n5x0%z46=_5yw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relationship_app',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Content Security Policy middleware sets CSP header to mitigate XSS risks
    'LibraryProject.security_middleware.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'demo_database',
        'USER': 'root',
        'PASSWORD': 'tilammg1234',
        'HOST': 'localhost',
        'PORT': 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/howto/manage-files/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-user-model
AUTH_USER_MODEL = 'relationship_app.CustomUser'

# Security settings
# NOTE: `DEBUG` is set to False here to reflect production-like settings.
# For local development, you may keep DEBUG=True but never deploy with it enabled.
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# HTTPS and Secure Cookies Configuration
# ===========================================
# These settings enforce HTTPS connections and secure cookie transmission.
# Enable these for production environments where HTTPS is configured.

# SECURE_PROXY_SSL_HEADER: Tell Django to trust the X-Forwarded-Proto header from reverse proxy.
# Use this when Django runs behind a reverse proxy (Nginx, Apache) that handles HTTPS.
# Format: ('HTTP_<HEADER_NAME>', '<EXPECTED_VALUE>')
# The proxy must set X-Forwarded-Proto: https for Django to recognize HTTPS connections.
# NOTE: Only enable if you trust the reverse proxy; misconfiguration can bypass HTTPS checks.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SECURE_SSL_REDIRECT: Redirect all non-HTTPS requests to HTTPS.
# NOTE: Set to False during local development (localhost doesn't support HTTPS by default).
# For production, set to True once SSL/TLS certificates are installed on the web server.
# When using a reverse proxy, ensure it sets X-Forwarded-Proto header correctly.
SECURE_SSL_REDIRECT = False  # Change to True in production

# SECURE_HSTS_SECONDS: HTTP Strict Transport Security (HSTS) max-age value.
# Instructs browsers to only access the site via HTTPS for the specified time (in seconds).
# 31536000 seconds = 1 year. Browsers will remember to use HTTPS even if user types 'http://'.
# NOTE: Only enable after confirming HTTPS is working; HSTS cannot be undone for the max-age period.
SECURE_HSTS_SECONDS = 31536000

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Include all subdomains in HSTS policy.
# If True, subdomains of your site will also be HTTPS-only. Enable for production.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allow your site to be included in the HSTS preload list.
# Browser vendors maintain a preload list of sites that should always use HTTPS.
# See https://hstspreload.org/ for details. Enable for production.
SECURE_HSTS_PRELOAD = True

# Ensure cookies are only sent over HTTPS in production
# SESSION_COOKIE_SECURE: Session cookies (user authentication) only sent over HTTPS.
# CSRF_COOKIE_SECURE: CSRF tokens only sent over HTTPS.
# NOTE: Set to False during local development if testing without HTTPS.
# In production with HTTPS, these should always be True.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Additional secure cookie settings
# SESSION_COOKIE_HTTPONLY: Prevent JavaScript from accessing session cookies (mitigates XSS).
SESSION_COOKIE_HTTPONLY = True

# CSRF_COOKIE_HTTPONLY: Prevent JavaScript from accessing CSRF cookies.
CSRF_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SAMESITE: Prevent CSRF attacks by restricting when cookies are sent cross-site.
# 'Strict': Cookie only sent in same-site requests.
# 'Lax': Cookie sent in top-level navigations and same-site requests.
# 'None': Cookie sent in all contexts (requires HTTPS).
# For production, 'Lax' or 'Strict' is recommended.
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF_COOKIE_SAMESITE: Apply SameSite restriction to CSRF cookies.
CSRF_COOKIE_SAMESITE = 'Lax'

# Content Security Policy settings used by our middleware below. Adjust as needed.
CSP_DEFAULT_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", 'data:')
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
