# Generated by Django 5.2.8 on 2025-11-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE api_book CHANGE COLUMN publication_date publication_year DATE NULL;",
            ],
            reverse_sql=[
                "ALTER TABLE api_book CHANGE COLUMN publication_year publication_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP;",
            ],
        ),
    ]
