from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import CustomUserViewSet

# Create an instance of the DefaultRouter
router = DefaultRouter()

# Register your CustomUserViewSet with the router
# The first argument 'users' defines the base path for all user endpoints.
router.register(r'users', CustomUserViewSet, basename='user')

# The urlpatterns list simply includes all the routes generated by the router
urlpatterns = [
    # Include all paths generated by the router (CRUD, follow, unfollow)
    path('', include(router.urls)),
]